version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - "11435:11434"
    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11435/
    depends_on:
      - ollama
    volumes:
      - ./webui-data:/app/backend/data
    restart: always